import { Claim, Package, TBCGap, CommissionGap, User } from './types';

export const mockUsers: User[] = [
  { id: '1', name: 'Alzbeta', email: 'alzbeta@ecogas.com', role: 'admin', roleType: 'Ecogas Staff', permissionRole: 'admin', assignedPackages: ['30402', '30403', '30404', '30405', '30406', '30407'], status: 'active' },
  { id: '2', name: 'Sarah Chen', email: 'sarah@ecogas.com', role: 'construction-manager', roleType: 'Ecogas Staff', permissionRole: 'construction-manager', assignedPackages: ['30402', '30403', '30404', '30405', '30406', '30407'], status: 'active' },
  { id: '3', name: 'Mike Johnson', email: 'mike@ecogas.com', role: 'construction-manager', roleType: 'Ecogas Staff', permissionRole: 'construction-manager', assignedPackages: ['30404', '30405', '30406'], status: 'active' },
  { id: '4', name: 'Hanham & Philp', email: 'claims@hanhamphilp.co.nz', role: 'contractor', contractor: 'Hanham & Philp', roleType: 'Construction Contractor', permissionRole: 'contractor', assignedPackages: ['30402', '30403'], status: 'active' },
  { id: '5', name: 'LPS', email: 'claims@lps.co.nz', role: 'contractor', contractor: 'LPS', roleType: 'Construction Contractor', permissionRole: 'contractor', assignedPackages: ['30404', '30406'], status: 'active' },
  { id: '6', name: 'P/Work Contractor', email: 'claims@pwork.example', role: 'contractor', contractor: 'P/Work Contractor', roleType: 'Construction Contractor', permissionRole: 'contractor', assignedPackages: ['30404', '30405', '30406'], status: 'active' },
  { id: '7', name: 'Reliant', email: 'claims@reliant.example', role: 'contractor', contractor: 'Reliant', roleType: 'Construction Contractor', permissionRole: 'contractor', assignedPackages: ['30405', '30406'], status: 'active' },
  { id: '8', name: 'Biocon / BioC', email: 'claims@bioc.example', role: 'contractor', contractor: 'Biocon / BioC', roleType: 'Design Consultant / Supply', permissionRole: 'contractor', assignedPackages: ['30405', '30406'], status: 'active' },
];

export const contractors = [
  'Hanham & Philp',
  'LPS',
  'P/Work Contractor',
  'Precia Molen',
  'Biocon / BioC',
  'Reliant',
  'Milenium',
  'Vortex',
  'Stevens',
  'Brickhouse / Drycake',
  'Protranz',
  'D&B Contractor',
  'Orion Nominated',
  'PFC',
  'S&H',
  'Port Hills',
  'Lutra',
  'Dorset',
  'Graintech',
  'Stronga',
  'LMS',
  'Lyttleton',
  'TM Consultants',
  'ENGEO',
  'Connectic',
  'PEG',
  'Electronet',
  'Vent Provider',
  'Drainlayer',
  'MPS',
];

export const contractorPackages: Record<string, string[]> = {
  // 30402 Civil & Buildings
  'Hanham & Philp': ['30402', '30403'],
  'Protranz': ['30402'],
  'Precia Molen': ['30402', '30407'],
  'PFC': ['30402', '30407'],
  'S&H': ['30402', '30403'],
  'D&B Contractor': ['30402'],
  'TM Consultants': ['30402'],
  'ENGEO': ['30402'],
  'Connectic': ['30402'],
  'Orion Nominated': ['30402', '30407'],
  // 30403 Reception Hall
  'Vortex': ['30403'],
  'Port Hills': ['30403'],
  // 30404 Processing
  'Stevens': ['30404'],
  'LPS': ['30404', '30406'],
  'Brickhouse / Drycake': ['30404'],
  'PEG': ['30404', '30405', '30406'],
  'P/Work Contractor': ['30404', '30405', '30406'],
  'MPS': ['30404'],
  // 30405 AD System
  'Reliant': ['30405', '30406'],
  'Biocon / BioC': ['30405', '30406'],
  'Electronet': ['30405'],
  // 30406 Process Output
  'Lutra': ['30406'],
  'Dorset': ['30406'],
  'Graintech': ['30406'],
  'Stronga': ['30406'],
  'LMS': ['30406'],
  'Lyttleton': ['30406'],
  'Vent Provider': ['30406'],
  'Drainlayer': ['30406'],
  // 30407 Electrical
  'Milenium': ['30407'],
};

export const mockPackages: Package[] = [
  {
    id: '30402',
    name: 'Civil & Buildings',
    responsibilityCode: 'NB/PS',
    contractors: ['Hanham & Philp', 'Protranz', 'Precia Molen', 'PFC', 'S&H', 'D&B Contractor', 'TM Consultants', 'ENGEO', 'Connectic', 'Orion Nominated'],
    jobCodes: [
      { code: '2111-2113', description: 'Site Establishment', deliveryPhase: 'Design', assignedContractor: 'Hanham & Philp', roleType: 'Construction Contractor', contractValue: 250000, openClaims: 2, gapFlag: false },
      { code: '2121-2123', description: 'Site Development', deliveryPhase: 'Construct', assignedContractor: 'Protranz', roleType: 'Construction Contractor', contractValue: 320000, openClaims: 1, gapFlag: false },
      { code: '2205-2250', description: 'Building & Truck Yard Stage 1', deliveryPhase: 'Construct', assignedContractor: 'Hanham & Philp', roleType: 'Construction Contractor', contractValue: 580000, openClaims: 3, gapFlag: false },
      { code: '2305-2330', description: 'AD Foundations Stage 2', deliveryPhase: 'Construct', assignedContractor: 'Hanham & Philp', roleType: 'Construction Contractor', contractValue: 420000, openClaims: 0, gapFlag: false },
      { code: '2405-2430', description: 'Storm Water & FW System', deliveryPhase: 'Supply / Procurement', assignedContractor: 'PFC', roleType: 'Design Consultant', contractValue: 180000, openClaims: 1, gapFlag: true },
      { code: '2990', description: 'Contingency', deliveryPhase: 'Design', roleType: 'Management', contractValue: 150000, openClaims: 0, gapFlag: false },
    ],
    openClaims: 7,
    valueAtRisk: 420000,
    tbcGaps: 2,
    commissionGaps: 1,
  },
  {
    id: '30403',
    name: 'Reception Hall',
    responsibilityCode: 'NB/PS',
    contractors: ['Vortex', 'Hanham & Philp', 'Port Hills', 'S&H'],
    jobCodes: [
      { code: '3205-3235', description: 'Ventilation', deliveryPhase: 'Supply / Procurement', assignedContractor: 'Vortex', roleType: 'Construction Contractor', contractValue: 280000, openClaims: 2, gapFlag: false },
      { code: '3305-3355', description: 'Biofilter', deliveryPhase: 'Construct', assignedContractor: 'TBC', roleType: 'Placeholder / TBC', contractValue: 320000, openClaims: 1, gapFlag: true },
      { code: '3990', description: 'Contingency', deliveryPhase: 'Design', roleType: 'Management', contractValue: 100000, openClaims: 0, gapFlag: false },
    ],
    openClaims: 3,
    valueAtRisk: 320000,
    tbcGaps: 1,
    commissionGaps: 0,
  },
  {
    id: '30404',
    name: 'Processing',
    responsibilityCode: 'BG',
    contractors: ['Stevens', 'LPS', 'Brickhouse / Drycake', 'PEG', 'P/Work Contractor', 'MPS'],
    jobCodes: [
      { code: '4105-4125', description: 'FOGO & Green Processing / Maceration', deliveryPhase: 'Supply / Procurement', assignedContractor: 'LPS', roleType: 'Construction Contractor', contractValue: 450000, openClaims: 3, gapFlag: false },
      { code: '4205-4225', description: 'Degritting', deliveryPhase: 'Construct', assignedContractor: 'Brickhouse / Drycake', roleType: 'Construction Contractor', contractValue: 380000, openClaims: 2, gapFlag: false },
      { code: '4990-4991', description: 'Contingency', deliveryPhase: 'Design', assignedContractor: 'MPS or other', roleType: 'Placeholder / TBC', contractValue: 120000, openClaims: 0, gapFlag: true },
    ],
    openClaims: 5,
    valueAtRisk: 850000,
    tbcGaps: 3,
    commissionGaps: 2,
  },
  {
    id: '30405',
    name: 'AD System',
    responsibilityCode: 'BG / AB',
    contractors: ['Reliant', 'Biocon / BioC', 'Electronet', 'P/Work Contractor', 'PEG'],
    jobCodes: [
      { code: '5105-5135', description: 'Process Water', deliveryPhase: 'Supply / Procurement', assignedContractor: 'Reliant', roleType: 'Construction Contractor', contractValue: 280000, openClaims: 1, gapFlag: true },
      { code: '5211-5214', description: 'Anaerobic Digestion', deliveryPhase: 'Construct', assignedContractor: 'Biocon / BioC', roleType: 'Design Consultant / Supply', contractValue: 520000, openClaims: 2, gapFlag: false },
      { code: '5221-5230', description: 'AD Tanks x4', deliveryPhase: 'Construct', assignedContractor: 'Reliant', roleType: 'Construction Contractor', contractValue: 760000, openClaims: 2, gapFlag: false },
      { code: '5305-5345', description: 'Transfer Pumps & Pipes', deliveryPhase: 'Construct', assignedContractor: 'P/Work Contractor', roleType: 'Construction Contractor', contractValue: 390000, openClaims: 3, gapFlag: false },
      { code: '5990-5991', description: 'Contingency', deliveryPhase: 'Commission', assignedContractor: 'TBC', roleType: 'Placeholder / TBC', contractValue: 100000, openClaims: 0, gapFlag: true },
    ],
    openClaims: 6,
    valueAtRisk: 1200000,
    tbcGaps: 2,
    commissionGaps: 3,
  },
  {
    id: '30406',
    name: 'Process Output',
    responsibilityCode: 'AB / BG',
    contractors: ['LPS', 'Lutra', 'Biocon / BioC', 'Reliant', 'LMS', 'Lyttleton', 'Dorset', 'Graintech', 'Stronga', 'Vent Provider', 'PEG', 'P/Work Contractor', 'Drainlayer'],
    jobCodes: [
      { code: '6111-6117', description: 'Digestate Processing', deliveryPhase: 'Supply / Procurement', assignedContractor: 'LPS', roleType: 'Construction Contractor', contractValue: 450000, openClaims: 2, gapFlag: false },
      { code: '6121-6126', description: 'Digestate Storage Tank', deliveryPhase: 'Construct', assignedContractor: 'Reliant', roleType: 'Construction Contractor', contractValue: 320000, openClaims: 1, gapFlag: false },
      { code: '6131-6136', description: 'Digestate Loadout', deliveryPhase: 'Construct', assignedContractor: 'P/Work Contractor', roleType: 'Construction Contractor', contractValue: 260000, openClaims: 1, gapFlag: true },
      { code: '6401-6495', description: 'Gas & Heating', deliveryPhase: 'Construct', assignedContractor: 'Biocon / BioC', roleType: 'Construction Contractor', contractValue: 580000, openClaims: 4, gapFlag: false },
      { code: '6505-6535', description: 'Biofuel Processing & Loading', deliveryPhase: 'Commission', assignedContractor: 'Dorset', roleType: 'Construction Contractor', contractValue: 420000, openClaims: 2, gapFlag: true },
      { code: '6990-6991', description: 'Contingency', deliveryPhase: 'Handover Docs', roleType: 'Management', contractValue: 100000, openClaims: 0, gapFlag: false },
    ],
    openClaims: 9,
    valueAtRisk: 1650000,
    tbcGaps: 2,
    commissionGaps: 2,
  },
  {
    id: '30407',
    name: 'Electrical',
    responsibilityCode: 'NB/PS',
    contractors: ['Milenium', 'Orion Nominated', 'Precia Molen', 'PFC'],
    jobCodes: [
      { code: '7105-7115', description: 'Power', deliveryPhase: 'Supply / Procurement', assignedContractor: 'Milenium', roleType: 'Construction Contractor', contractValue: 280000, openClaims: 1, gapFlag: false },
      { code: '7211-7214', description: 'Process Control', deliveryPhase: 'Construct', assignedContractor: 'Milenium', roleType: 'Construction Contractor', contractValue: 320000, openClaims: 2, gapFlag: false },
      { code: '7221-7222', description: 'Compressed Air', deliveryPhase: 'Construct', assignedContractor: 'Milenium', roleType: 'Construction Contractor', contractValue: 160000, openClaims: 0, gapFlag: false },
      { code: '7305-7335', description: 'IT & Networking', deliveryPhase: 'Construct', assignedContractor: 'Milenium', roleType: 'Construction Contractor', contractValue: 190000, openClaims: 0, gapFlag: false },
      { code: '7405-7420', description: 'Security', deliveryPhase: 'Supply / Procurement', assignedContractor: 'TBC', roleType: 'Placeholder / TBC', contractValue: 210000, openClaims: 0, gapFlag: true },
      { code: '7505', description: 'Weighbridge', deliveryPhase: 'Commission', assignedContractor: 'Precia Molen', roleType: 'Construction Contractor', contractValue: 95000, openClaims: 0, gapFlag: false },
      { code: '7990', description: 'Contingency', deliveryPhase: 'Design', roleType: 'Management', contractValue: 80000, openClaims: 0, gapFlag: true },
    ],
    openClaims: 3,
    valueAtRisk: 450000,
    tbcGaps: 1,
    commissionGaps: 1,
  },
];

export const mockClaims: Claim[] = [
  {
    id: 'CLM-30402-001',
    type: 'Claim',
    packageId: '30402',
    packageName: 'Civil & Buildings',
    responsibilityCode: 'NB/PS',
    jobCode: '2111',
    jobDescription: 'Site Establishment',
    contractorId: '1',
    contractorName: 'Hanham & Philp',
    deliveryPhase: 'Design',
    value: 45000,
    submitted: '2024-06-15',
    deadline: '2024-07-15',
    status: 'Under Review',
    riskFlag: 'Due Soon',
    owner: 'Sarah Chen',
    ownerRole: 'Construction Manager',
    daysStatus: 3,
    auditTrail: [
      { timestamp: '2024-06-20', user: 'Hanham & Philp', action: 'Submitted', details: 'Initial submission' },
      { timestamp: '2024-06-21', user: 'Sarah Chen', action: 'Under Review', details: 'Assigned for review' },
    ],
    documents: ['site-plan.pdf', 'budget-breakdown.xlsx'],
  },
  {
    id: 'VO-30402-018',
    type: 'VO',
    packageId: '30402',
    packageName: 'Civil & Buildings',
    responsibilityCode: 'NB/PS',
    jobCode: '2205',
    jobDescription: 'Building Stage 1',
    contractorId: '1',
    contractorName: 'Hanham & Philp',
    deliveryPhase: 'Construct',
    value: 125000,
    submitted: '2024-06-18',
    deadline: '2024-07-18',
    status: 'Submitted',
    riskFlag: 'Submitted',
    owner: 'Sarah Chen',
    ownerRole: 'Construction Manager',
    daysStatus: 12,
    auditTrail: [
      { timestamp: '2024-06-18', user: 'Hanham & Philp', action: 'Submitted', details: 'Variation order submitted' },
    ],
    documents: ['vo-amendment.pdf'],
  },
  {
    id: 'RFI-30405-011',
    type: 'RFI',
    packageId: '30405',
    packageName: 'AD System',
    responsibilityCode: 'BG / AB',
    jobCode: '5211',
    jobDescription: 'Anaerobic Digestion',
    contractorId: '2',
    contractorName: 'Reliant',
    deliveryPhase: 'Construct',
    value: 0,
    submitted: '2024-06-10',
    deadline: '2024-06-24',
    status: 'Overdue',
    riskFlag: 'Overdue',
    owner: 'Mike Johnson',
    ownerRole: 'Construction Manager',
    daysStatus: -6,
    auditTrail: [
      { timestamp: '2024-06-10', user: 'Reliant', action: 'Submitted', details: 'RFI submitted' },
      { timestamp: '2024-06-21', user: 'Mike Johnson', action: 'Assigned', details: 'Assigned for response' },
    ],
    documents: [],
  },
  {
    id: 'CLM-30405-022',
    type: 'Claim',
    packageId: '30405',
    packageName: 'AD System',
    responsibilityCode: 'BG / AB',
    jobCode: '5305',
    jobDescription: 'Transfer Pumps & Pipes',
    contractorId: '3',
    contractorName: 'P/Work Contractor',
    deliveryPhase: 'Construct',
    value: 85000,
    submitted: '2024-06-17',
    deadline: '2024-07-17',
    status: 'More Info Requested',
    riskFlag: 'Under Review',
    owner: 'Sarah Chen',
    ownerRole: 'Construction Manager',
    daysStatus: 5,
    auditTrail: [
      { timestamp: '2024-06-17', user: 'P/Work Contractor', action: 'Submitted', details: 'Claim submitted' },
      { timestamp: '2024-06-19', user: 'Sarah Chen', action: 'More Info Requested', details: 'Requesting additional documentation' },
    ],
    documents: ['invoice.pdf'],
  },
  {
    id: 'VO-30406-022',
    type: 'VO',
    packageId: '30406',
    packageName: 'Process Output',
    responsibilityCode: 'AB / BG',
    jobCode: '6401',
    jobDescription: 'Gas & Heating',
    contractorId: '4',
    contractorName: 'Biocon / BioC',
    deliveryPhase: 'Construct',
    value: 245000,
    submitted: '2024-06-14',
    deadline: '2024-07-14',
    status: 'Under Review',
    riskFlag: 'Due Soon',
    owner: 'Mike Johnson',
    ownerRole: 'Construction Manager',
    daysStatus: 2,
    auditTrail: [
      { timestamp: '2024-06-14', user: 'Biocon / BioC', action: 'Submitted', details: 'Major variation submitted' },
      { timestamp: '2024-06-15', user: 'Mike Johnson', action: 'Under Review', details: 'Assigned for technical review' },
    ],
    documents: ['design-amendment.pdf', 'cost-breakdown.xlsx'],
  },
  {
    id: 'CLM-30406-035',
    type: 'Claim',
    packageId: '30406',
    packageName: 'Process Output',
    responsibilityCode: 'AB / BG',
    jobCode: '6111',
    jobDescription: 'Digestate Processing',
    contractorId: '4',
    contractorName: 'LPS',
    deliveryPhase: 'Supply / Procurement',
    value: 125000,
    submitted: '2024-06-19',
    deadline: '2024-07-19',
    status: 'Approved',
    riskFlag: 'Approved',
    owner: 'Sarah Chen',
    ownerRole: 'Construction Manager',
    daysStatus: 7,
    auditTrail: [
      { timestamp: '2024-06-19', user: 'LPS', action: 'Submitted', details: 'Claim submitted' },
      { timestamp: '2024-06-21', user: 'Sarah Chen', action: 'Approved', details: 'Approved for payment' },
    ],
    documents: ['invoice.pdf', 'delivery-certificate.pdf'],
  },
  {
    id: 'RFI-30407-005',
    type: 'RFI',
    packageId: '30407',
    packageName: 'Electrical',
    responsibilityCode: 'NB/PS',
    jobCode: '7205',
    jobDescription: 'Switchroom & Distribution',
    contractorId: '5',
    contractorName: 'Precia Molen',
    deliveryPhase: 'Construct',
    value: 0,
    submitted: '2024-06-12',
    deadline: '2024-06-26',
    status: 'Overdue',
    riskFlag: 'Overdue',
    owner: 'Mike Johnson',
    ownerRole: 'Construction Manager',
    daysStatus: -4,
    auditTrail: [
      { timestamp: '2024-06-12', user: 'Precia Molen', action: 'Submitted', details: 'RFI submitted for clarification' },
    ],
    documents: [],
  },
  {
    id: 'CLM-30404-042',
    type: 'Claim',
    packageId: '30404',
    packageName: 'Processing',
    responsibilityCode: 'BG',
    jobCode: '4205',
    jobDescription: 'Degritting',
    contractorId: '6',
    contractorName: 'Stevens',
    deliveryPhase: 'Construct',
    value: 75000,
    submitted: '2024-06-16',
    deadline: '2024-07-16',
    status: 'Rejected',
    riskFlag: 'Rejected',
    owner: 'Sarah Chen',
    ownerRole: 'Construction Manager',
    daysStatus: 6,
    auditTrail: [
      { timestamp: '2024-06-16', user: 'Stevens', action: 'Submitted', details: 'Claim submitted' },
      { timestamp: '2024-06-18', user: 'Sarah Chen', action: 'Rejected', details: 'Incomplete documentation' },
    ],
    documents: ['partial-invoice.pdf'],
  },
  {
    id: 'CLM-30403-015',
    type: 'Claim',
    packageId: '30403',
    packageName: 'Reception Hall',
    responsibilityCode: 'NB/PS',
    jobCode: '3205',
    jobDescription: 'Ventilation',
    contractorId: '7',
    contractorName: 'Vortex',
    deliveryPhase: 'Supply / Procurement',
    value: 95000,
    submitted: '2024-06-13',
    deadline: '2024-07-13',
    status: 'Submitted',
    riskFlag: 'Submitted',
    owner: 'Sarah Chen',
    ownerRole: 'Construction Manager',
    daysStatus: 11,
    auditTrail: [
      { timestamp: '2024-06-13', user: 'Vortex', action: 'Submitted', details: 'Supply claim submitted' },
    ],
    documents: ['supply-invoice.pdf'],
  },
  {
    id: 'EOT-30402-008',
    type: 'EOT',
    packageId: '30402',
    packageName: 'Civil & Buildings',
    responsibilityCode: 'NB/PS',
    jobCode: '2121',
    jobDescription: 'Site Development',
    contractorId: '1',
    contractorName: 'Hanham & Philp',
    deliveryPhase: 'Construct',
    value: 65000,
    submitted: '2024-06-20',
    deadline: '2024-07-20',
    status: 'Under Review',
    riskFlag: 'Due Soon',
    owner: 'Sarah Chen',
    ownerRole: 'Construction Manager',
    daysStatus: 0,
    auditTrail: [
      { timestamp: '2024-06-20', user: 'Hanham & Philp', action: 'Submitted', details: 'Extension of time request' },
    ],
    documents: ['extension-justification.pdf'],
  },
  {
    id: 'CLM-30404-051',
    type: 'Claim',
    packageId: '30404',
    packageName: 'Processing',
    responsibilityCode: 'BG',
    jobCode: '4105',
    jobDescription: 'FOGO & Green Processing',
    contractorId: '8',
    contractorName: 'LPS',
    deliveryPhase: 'Supply / Procurement',
    value: 165000,
    submitted: '2024-06-08',
    deadline: '2024-06-22',
    status: 'Overdue',
    riskFlag: 'Overdue',
    owner: 'Mike Johnson',
    ownerRole: 'Construction Manager',
    daysStatus: -8,
    auditTrail: [
      { timestamp: '2024-06-08', user: 'LPS', action: 'Submitted', details: 'Supply claim' },
    ],
    documents: ['invoice-4105.pdf'],
  },
  {
    id: 'VO-30403-012',
    type: 'VO',
    packageId: '30403',
    packageName: 'Reception Hall',
    responsibilityCode: 'NB/PS',
    jobCode: '3305',
    jobDescription: 'Biofilter',
    contractorId: '9',
    contractorName: 'Hanham & Philp',
    deliveryPhase: 'Construct',
    value: 285000,
    submitted: '2024-06-21',
    deadline: '2024-07-21',
    status: 'Submitted',
    riskFlag: 'Submitted',
    owner: 'Sarah Chen',
    ownerRole: 'Construction Manager',
    daysStatus: 30,
    auditTrail: [
      { timestamp: '2024-06-21', user: 'Hanham & Philp', action: 'Submitted', details: 'Major scope change' },
    ],
    documents: ['vo-scope.pdf', 'revised-budget.xlsx'],
  },
  {
    id: 'CLM-30405-031',
    type: 'Claim',
    packageId: '30405',
    packageName: 'AD System',
    responsibilityCode: 'BG / AB',
    jobCode: '5105',
    jobDescription: 'Process Water',
    contractorId: '10',
    contractorName: 'P/Work Contractor',
    deliveryPhase: 'Supply / Procurement',
    value: 82000,
    submitted: '2024-06-11',
    deadline: '2024-06-25',
    status: 'Overdue',
    riskFlag: 'Overdue',
    owner: 'Mike Johnson',
    ownerRole: 'Construction Manager',
    daysStatus: -5,
    auditTrail: [
      { timestamp: '2024-06-11', user: 'P/Work Contractor', action: 'Submitted', details: 'Supply invoice' },
    ],
    documents: ['po-5105.pdf'],
  },
  {
    id: 'Design Change-30406-09',
    type: 'Design Change',
    packageId: '30406',
    packageName: 'Process Output',
    responsibilityCode: 'AB / BG',
    jobCode: '6505',
    jobDescription: 'Biofuel Processing & Loading',
    contractorId: '11',
    contractorName: 'Reliant',
    deliveryPhase: 'Commission',
    value: 335000,
    submitted: '2024-06-19',
    deadline: '2024-07-19',
    status: 'Under Review',
    riskFlag: 'Due Soon',
    owner: 'Mike Johnson',
    ownerRole: 'Construction Manager',
    daysStatus: 0,
    auditTrail: [
      { timestamp: '2024-06-19', user: 'Alzbeta', action: 'Submitted', details: 'Design change - critical equipment upgrade' },
    ],
    documents: ['design-spec-revision.pdf', 'equipment-schedule.xlsx'],
  },
  {
    id: 'RFI-30402-007',
    type: 'RFI',
    packageId: '30402',
    packageName: 'Civil & Buildings',
    responsibilityCode: 'NB/PS',
    jobCode: '2405',
    jobDescription: 'Storm Water & FW System',
    contractorId: '12',
    contractorName: 'PFC',
    deliveryPhase: 'Supply / Procurement',
    value: 0,
    submitted: '2024-06-09',
    deadline: '2024-06-23',
    status: 'Overdue',
    riskFlag: 'Overdue',
    owner: 'Sarah Chen',
    ownerRole: 'Construction Manager',
    daysStatus: -7,
    auditTrail: [
      { timestamp: '2024-06-09', user: 'PFC', action: 'Submitted', details: 'RFI - drainage specification' },
    ],
    documents: [],
  },
  {
    id: 'CLM-30406-043',
    type: 'Claim',
    packageId: '30406',
    packageName: 'Process Output',
    responsibilityCode: 'AB / BG',
    jobCode: '6121',
    jobDescription: 'Digestate Storage Tank',
    contractorId: '13',
    contractorName: 'Stronga',
    deliveryPhase: 'Construct',
    value: 195000,
    submitted: '2024-06-20',
    deadline: '2024-07-20',
    status: 'Submitted',
    riskFlag: 'Submitted',
    owner: 'Sarah Chen',
    ownerRole: 'Construction Manager',
    daysStatus: 30,
    auditTrail: [
      { timestamp: '2024-06-20', user: 'Stronga', action: 'Submitted', details: 'Tank fabrication & delivery claim' },
    ],
    documents: ['invoice-tank.pdf', 'delivery-docket.pdf'],
  },
  {
    id: 'CLM-30407-019',
    type: 'Claim',
    packageId: '30407',
    packageName: 'Electrical',
    responsibilityCode: 'NB/PS',
    jobCode: '7105',
    jobDescription: '11kV Connection',
    contractorId: '14',
    contractorName: 'PFC',
    deliveryPhase: 'Supply / Procurement',
    value: 142000,
    submitted: '2024-06-22',
    deadline: '2024-07-22',
    status: 'Submitted',
    riskFlag: 'Submitted',
    owner: 'Sarah Chen',
    ownerRole: 'Construction Manager',
    daysStatus: 30,
    auditTrail: [
      { timestamp: '2024-06-22', user: 'PFC', action: 'Submitted', details: '11kV connection supply & install' },
    ],
    documents: ['supply-invoice.pdf', 'connection-cert.pdf'],
  },
  {
    id: 'CLM-30403-026',
    type: 'Claim',
    packageId: '30403',
    packageName: 'Reception Hall',
    responsibilityCode: 'NB/PS',
    jobCode: '3305',
    jobDescription: 'Biofilter',
    contractorId: '15',
    contractorName: 'Port Hills',
    deliveryPhase: 'Construct',
    value: 52000,
    submitted: '2024-06-23',
    deadline: '2024-07-23',
    status: 'Submitted',
    riskFlag: 'Submitted',
    owner: 'Sarah Chen',
    ownerRole: 'Construction Manager',
    daysStatus: 30,
    auditTrail: [
      { timestamp: '2024-06-23', user: 'Port Hills', action: 'Submitted', details: 'Labor and materials claim' },
    ],
    documents: ['timesheet.pdf', 'material-receipts.pdf'],
  },
  {
    id: 'VO-30404-031',
    type: 'VO',
    packageId: '30404',
    packageName: 'Processing',
    responsibilityCode: 'BG',
    jobCode: '4205',
    jobDescription: 'Degritting',
    contractorId: '16',
    contractorName: 'Brickhouse / Drycake',
    deliveryPhase: 'Construct',
    value: 145000,
    submitted: '2024-06-17',
    deadline: '2024-07-17',
    status: 'Under Review',
    riskFlag: 'Under Review',
    owner: 'Mike Johnson',
    ownerRole: 'Construction Manager',
    daysStatus: 5,
    auditTrail: [
      { timestamp: '2024-06-17', user: 'Brickhouse / Drycake', action: 'Submitted', details: 'Scope variation - additional scuffing stage' },
      { timestamp: '2024-06-21', user: 'Mike Johnson', action: 'Under Review', details: 'Technical review in progress' },
    ],
    documents: ['vo-spec.pdf'],
  },
  {
    id: 'CLM-30402-037',
    type: 'Claim',
    packageId: '30402',
    packageName: 'Civil & Buildings',
    responsibilityCode: 'NB/PS',
    jobCode: '2205',
    jobDescription: 'Building Stage 1',
    contractorId: '17',
    contractorName: 'Protranz',
    deliveryPhase: 'Construct',
    value: 225000,
    submitted: '2024-06-24',
    deadline: '2024-07-24',
    status: 'Submitted',
    riskFlag: 'Submitted',
    owner: 'Sarah Chen',
    ownerRole: 'Construction Manager',
    daysStatus: 30,
    auditTrail: [
      { timestamp: '2024-06-24', user: 'Protranz', action: 'Submitted', details: 'Concrete works progress claim' },
    ],
    documents: ['invoice-batch3.pdf', 'progress-photos.pdf'],
  },
  {
    id: 'RFI-30406-014',
    type: 'RFI',
    packageId: '30406',
    packageName: 'Process Output',
    responsibilityCode: 'AB / BG',
    jobCode: '6401',
    jobDescription: 'Gas & Heating',
    contractorId: '18',
    contractorName: 'Lutra',
    deliveryPhase: 'Construct',
    value: 0,
    submitted: '2024-06-07',
    deadline: '2024-06-21',
    status: 'Overdue',
    riskFlag: 'Overdue',
    owner: 'Mike Johnson',
    ownerRole: 'Construction Manager',
    daysStatus: -9,
    auditTrail: [
      { timestamp: '2024-06-07', user: 'Lutra', action: 'Submitted', details: 'RFI - heating system specification' },
    ],
    documents: [],
  },
  {
    id: 'CLM-30405-048',
    type: 'Claim',
    packageId: '30405',
    packageName: 'AD System',
    responsibilityCode: 'BG / AB',
    jobCode: '5211',
    jobDescription: 'Anaerobic Digestion',
    contractorId: '19',
    contractorName: 'Biocon / BioC',
    deliveryPhase: 'Construct',
    value: 325000,
    submitted: '2024-06-25',
    deadline: '2024-07-25',
    status: 'Submitted',
    riskFlag: 'Submitted',
    owner: 'Mike Johnson',
    ownerRole: 'Construction Manager',
    daysStatus: 30,
    auditTrail: [
      { timestamp: '2024-06-25', user: 'Biocon / BioC', action: 'Submitted', details: 'AD vessel installation and testing' },
    ],
    documents: ['invoice-vessel.pdf', 'test-results.pdf', 'compliance-cert.pdf'],
  },
  {
    id: 'VO-30407-006',
    type: 'VO',
    packageId: '30407',
    packageName: 'Electrical',
    responsibilityCode: 'NB/PS',
    jobCode: '7205',
    jobDescription: 'Switchroom & Distribution',
    contractorId: '20',
    contractorName: 'Precia Molen',
    deliveryPhase: 'Construct',
    value: 95000,
    submitted: '2024-06-26',
    deadline: '2024-07-26',
    status: 'Submitted',
    riskFlag: 'Submitted',
    owner: 'Sarah Chen',
    ownerRole: 'Construction Manager',
    daysStatus: 30,
    auditTrail: [
      { timestamp: '2024-06-26', user: 'Precia Molen', action: 'Submitted', details: 'Additional circuit upgrades' },
    ],
    documents: ['electrical-spec-rev2.pdf'],
  },
  {
    id: 'RFI-30403-008',
    type: 'RFI',
    packageId: '30403',
    packageName: 'Reception Hall',
    responsibilityCode: 'NB/PS',
    jobCode: '3305',
    jobDescription: 'Biofilter',
    contractorId: '21',
    contractorName: 'S&H',
    deliveryPhase: 'Construct',
    value: 0,
    submitted: '2024-06-27',
    deadline: '2024-07-11',
    status: 'Under Review',
    riskFlag: 'Due Soon',
    owner: 'Mike Johnson',
    ownerRole: 'Construction Manager',
    daysStatus: 1,
    auditTrail: [
      { timestamp: '2024-06-27', user: 'S&H', action: 'Submitted', details: 'Biofilter performance specification query' },
    ],
    documents: [],
  },
  {
    id: 'CLM-30402-045',
    type: 'Claim',
    packageId: '30402',
    packageName: 'Civil & Buildings',
    responsibilityCode: 'NB/PS',
    jobCode: '2111',
    jobDescription: 'Site Establishment',
    contractorId: '22',
    contractorName: 'D&B Contractor',
    deliveryPhase: 'Design',
    value: 55000,
    submitted: '2024-06-28',
    deadline: '2024-07-28',
    status: 'Submitted',
    riskFlag: 'Submitted',
    owner: 'Sarah Chen',
    ownerRole: 'Construction Manager',
    daysStatus: 30,
    auditTrail: [
      { timestamp: '2024-06-28', user: 'D&B Contractor', action: 'Submitted', details: 'Site access and safety setup costs' },
    ],
    documents: ['site-access-report.pdf', 'safety-plan.pdf'],
  },
  {
    id: 'Design Change-30405-10',
    type: 'Design Change',
    packageId: '30405',
    packageName: 'AD System',
    responsibilityCode: 'BG / AB',
    jobCode: '5211',
    jobDescription: 'Anaerobic Digestion',
    contractorId: '23',
    contractorName: 'Electronet',
    deliveryPhase: 'Supply / Procurement',
    value: 185000,
    submitted: '2024-06-29',
    deadline: '2024-07-29',
    status: 'Submitted',
    riskFlag: 'Submitted',
    owner: 'Mike Johnson',
    ownerRole: 'Construction Manager',
    daysStatus: 30,
    auditTrail: [
      { timestamp: '2024-06-29', user: 'Alzbeta', action: 'Submitted', details: 'Design change - AD heating system upgrade to include redundancy' },
    ],
    documents: ['redundancy-design.pdf', 'cost-adjustment.xlsx'],
  },
  {
    id: 'CLM-30406-056',
    type: 'Claim',
    packageId: '30406',
    packageName: 'Process Output',
    responsibilityCode: 'AB / BG',
    jobCode: '6601',
    jobDescription: 'Commissioning & Testing Documentation',
    contractorId: '24',
    contractorName: 'Stronga',
    deliveryPhase: 'Compliance Docs',
    value: 45000,
    submitted: '2024-06-30',
    deadline: '2024-07-30',
    status: 'Submitted',
    riskFlag: 'Submitted',
    owner: 'Sarah Chen',
    ownerRole: 'Construction Manager',
    daysStatus: 30,
    auditTrail: [
      { timestamp: '2024-06-30', user: 'Stronga', action: 'Submitted', details: 'Compliance documentation and test certificates' },
    ],
    documents: ['test-certs.pdf', 'compliance-report.pdf'],
  },
  {
    id: 'CLM-30407-028',
    type: 'Claim',
    packageId: '30407',
    packageName: 'Electrical',
    responsibilityCode: 'NB/PS',
    jobCode: '7990',
    jobDescription: 'Handover & As-Built Documentation',
    contractorId: '25',
    contractorName: 'PFC',
    deliveryPhase: 'Handover Docs',
    value: 35000,
    submitted: '2024-07-01',
    deadline: '2024-07-31',
    status: 'Submitted',
    riskFlag: 'Submitted',
    owner: 'Sarah Chen',
    ownerRole: 'Construction Manager',
    daysStatus: 30,
    auditTrail: [
      { timestamp: '2024-07-01', user: 'PFC', action: 'Submitted', details: 'As-built drawings and handover documentation' },
    ],
    documents: ['as-built-drawings.pdf', 'o-and-m-manuals.pdf'],
  },
];

export const mockTBCGaps: TBCGap[] = [
  // Pre-processing CFO Fully Unassigned (Package 30404 - Processing)
  {
    id: 'TBC-30404-CFO-01',
    packageId: '30404',
    packageName: 'Processing',
    jobCode: 'CFO-Loader',
    scope: 'Loader - Pre-processing',
    supplyContractor: undefined,
    commissionContractor: undefined,
    deliveryPhase: 'Supply / Procurement',
    riskLevel: 'Urgent',
  },
  {
    id: 'TBC-30404-CFO-02',
    packageId: '30404',
    packageName: 'Processing',
    jobCode: 'CFO-Forklift',
    scope: 'Forklift - Pre-processing',
    supplyContractor: undefined,
    commissionContractor: undefined,
    deliveryPhase: 'Supply / Procurement',
    riskLevel: 'Urgent',
  },
  {
    id: 'TBC-30404-CFO-03',
    packageId: '30404',
    packageName: 'Processing',
    jobCode: 'CFO-Irrigation',
    scope: 'Irrigation - Pre-processing',
    supplyContractor: undefined,
    commissionContractor: undefined,
    deliveryPhase: 'Supply / Procurement',
    riskLevel: 'Urgent',
  },
  {
    id: 'TBC-30404-CFO-04',
    packageId: '30404',
    packageName: 'Processing',
    jobCode: 'CFO-Depacker',
    scope: 'Depacker with hopper - Pre-processing',
    supplyContractor: undefined,
    commissionContractor: undefined,
    deliveryPhase: 'Supply / Procurement',
    riskLevel: 'Urgent',
  },
  {
    id: 'TBC-30404-CFO-05',
    packageId: '30404',
    packageName: 'Processing',
    jobCode: 'CFO-Press',
    scope: 'Screw Press - Pre-processing',
    supplyContractor: undefined,
    commissionContractor: undefined,
    deliveryPhase: 'Supply / Procurement',
    riskLevel: 'Urgent',
  },
  {
    id: 'TBC-30404-CFO-06',
    packageId: '30404',
    packageName: 'Processing',
    jobCode: 'CFO-SkipBin',
    scope: 'Skip Bin - Pre-processing',
    supplyContractor: undefined,
    commissionContractor: undefined,
    deliveryPhase: 'Supply / Procurement',
    riskLevel: 'Urgent',
  },
  {
    id: 'TBC-30404-CFO-07',
    packageId: '30404',
    packageName: 'Processing',
    jobCode: 'CFO-MagnetBox',
    scope: 'Magnet Box - Pre-processing',
    supplyContractor: undefined,
    commissionContractor: undefined,
    deliveryPhase: 'Supply / Procurement',
    riskLevel: 'Urgent',
  },
  {
    id: 'TBC-30404-CFO-08',
    packageId: '30404',
    packageName: 'Processing',
    jobCode: 'CFO-Pump',
    scope: 'Pump - Pre-processing',
    supplyContractor: undefined,
    commissionContractor: undefined,
    deliveryPhase: 'Supply / Procurement',
    riskLevel: 'Urgent',
  },
  {
    id: 'TBC-30404-CFO-09',
    packageId: '30404',
    packageName: 'Processing',
    jobCode: 'CFO-Macerator',
    scope: 'Macerator - Pre-processing',
    supplyContractor: undefined,
    commissionContractor: undefined,
    deliveryPhase: 'Supply / Procurement',
    riskLevel: 'Urgent',
  },
  {
    id: 'TBC-30404-CFO-10',
    packageId: '30404',
    packageName: 'Processing',
    jobCode: 'CFO-Bunkers',
    scope: 'Bunkers - Pre-processing',
    supplyContractor: undefined,
    commissionContractor: undefined,
    deliveryPhase: 'Supply / Procurement',
    riskLevel: 'Urgent',
  },
  {
    id: 'TBC-30404-CFO-11',
    packageId: '30404',
    packageName: 'Processing',
    jobCode: 'CFO-Support',
    scope: 'Support Structures - Pre-processing',
    supplyContractor: undefined,
    commissionContractor: undefined,
    deliveryPhase: 'Supply / Procurement',
    riskLevel: 'Urgent',
  },
  // Gap/TBC Urgent (with no supply contractor)
  {
    id: 'TBC-30405-001',
    packageId: '30405',
    packageName: 'AD System',
    jobCode: '5115',
    scope: 'Tank sensors / flanges / valves',
    supplyContractor: undefined,
    commissionContractor: undefined,
    deliveryPhase: 'Supply / Procurement',
    riskLevel: 'Urgent',
  },
  {
    id: 'TBC-30406-001',
    packageId: '30406',
    packageName: 'Process Output',
    jobCode: '6201',
    scope: 'Biosolids conveyors',
    supplyContractor: undefined,
    commissionContractor: undefined,
    deliveryPhase: 'Supply / Procurement',
    riskLevel: 'Urgent',
  },
  // Gap/TBC Standard (with no supply contractor)
  {
    id: 'TBC-30405-002',
    packageId: '30405',
    packageName: 'AD System',
    jobCode: '5125',
    scope: 'Tanker load-in control panel',
    supplyContractor: undefined,
    commissionContractor: undefined,
    deliveryPhase: 'Supply / Procurement',
    riskLevel: 'Standard',
  },
  {
    id: 'TBC-30402-001',
    packageId: '30402',
    packageName: 'Civil & Buildings',
    jobCode: '2150',
    scope: 'Site drainage interconnection',
    supplyContractor: undefined,
    commissionContractor: undefined,
    deliveryPhase: 'Design',
    riskLevel: 'Standard',
  },
  // Commission-phase TBC (supply confirmed, but commission contractor TBC)
  {
    id: 'TBC-30405-C001',
    packageId: '30405',
    packageName: 'AD System',
    jobCode: '5115-C',
    scope: 'Tank sensors / flanges - Commission phase',
    supplyContractor: 'Reliant',
    commissionContractor: undefined,
    deliveryPhase: 'Commission',
    riskLevel: 'Urgent',
  },
  {
    id: 'TBC-30405-C002',
    packageId: '30405',
    packageName: 'AD System',
    jobCode: '5211-C',
    scope: 'Anaerobic Digestion commissioning',
    supplyContractor: 'Biocon / BioC',
    commissionContractor: undefined,
    deliveryPhase: 'Commission',
    riskLevel: 'Standard',
  },
  {
    id: 'TBC-30406-C001',
    packageId: '30406',
    packageName: 'Process Output',
    jobCode: '6401-C',
    scope: 'Gas heating system commissioning',
    supplyContractor: 'LPS',
    commissionContractor: undefined,
    deliveryPhase: 'Commission',
    riskLevel: 'Urgent',
  },
];

export const mockCommissionGaps: CommissionGap[] = [
  {
    id: 'CG-30405-001',
    packageId: '30405',
    packageName: 'AD System',
    jobCode: '5135',
    scope: 'Heaters commission phase across AD farm',
    supplyContractor: 'Reliant',
    commissionContractor: undefined,
    deliveryPhase: 'Commission',
    riskLevel: 'Urgent',
  },
  {
    id: 'CG-30405-002',
    packageId: '30405',
    packageName: 'AD System',
    jobCode: '5230',
    scope: 'Mixers commission phase',
    supplyContractor: 'Reliant',
    commissionContractor: undefined,
    deliveryPhase: 'Commission',
    riskLevel: 'Standard',
  },
  {
    id: 'CG-30405-003',
    packageId: '30405',
    packageName: 'AD System',
    jobCode: '5305-C',
    scope: 'Transfer Pumps & Pipes commissioning',
    supplyContractor: 'P/Work Contractor',
    commissionContractor: undefined,
    deliveryPhase: 'Commission',
    riskLevel: 'Urgent',
  },
  {
    id: 'CG-30406-001',
    packageId: '30406',
    packageName: 'Process Output',
    jobCode: '6121-C',
    scope: 'Digestate processing commissioning',
    supplyContractor: 'LPS',
    commissionContractor: undefined,
    deliveryPhase: 'Commission',
    riskLevel: 'Urgent',
  },
  {
    id: 'CG-30406-002',
    packageId: '30406',
    packageName: 'Process Output',
    jobCode: '6505',
    scope: 'Dryers / heaters commissioning',
    supplyContractor: 'Stronga',
    commissionContractor: undefined,
    deliveryPhase: 'Commission',
    riskLevel: 'Standard',
  },
  {
    id: 'CG-30406-003',
    packageId: '30406',
    packageName: 'Process Output',
    jobCode: '6401-C',
    scope: 'Gas & heating system commissioning',
    supplyContractor: 'Biocon / BioC',
    commissionContractor: undefined,
    deliveryPhase: 'Commission',
    riskLevel: 'Standard',
  },
];
